// <auto-generated />
using System;
using Maintenance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maintenance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416144623_AddAlertSettingsSeed")]
    partial class AddAlertSettingsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maintenance.API.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressePrestataire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDenonciation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelaiPreavisMois")
                        .HasColumnType("int");

                    b.Property<string>("IdPropriete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantHtAnnuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Prestataire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prestation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("StatutDenonciation")
                        .HasColumnType("int");

                    b.Property<int>("StatutValidation")
                        .HasColumnType("int");

                    b.Property<string>("TypeBien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Maintenance.API.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "preavis_default_mois",
                            Value = "3"
                        },
                        new
                        {
                            Id = 2,
                            Key = "alert_6mois",
                            Value = "true"
                        },
                        new
                        {
                            Id = 3,
                            Key = "alert_3mois",
                            Value = "true"
                        },
                        new
                        {
                            Id = 4,
                            Key = "alert_1mois",
                            Value = "true"
                        },
                        new
                        {
                            Id = 5,
                            Key = "alert_depasse",
                            Value = "true"
                        },
                        new
                        {
                            Id = 6,
                            Key = "alert_email",
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            Key = "alert_copie_client",
                            Value = "false"
                        },
                        new
                        {
                            Id = 8,
                            Key = "alert_resume_hebdo",
                            Value = "false"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
